### ISSUE TITLE
Got error with terraform init for aws-examples/blog-post/aws 

### ISSUE THREAD

**Issue by cf250024** [pangeo-data/terraform-deploy#49]
When I try to run `terraform init`, I got an error as follows.

```
Error: Unsupported Terraform Core version

  on .terraform/modules/iam_assumable_role_admin/modules/iam-assumable-role-with-oidc/versions.tf line 2, in terraform:
   2:   required_version = "~> 0.12.6"

Module module.iam_assumable_role_admin (from
terraform-aws-modules/iam/aws//modules/iam-assumable-role-with-oidc) does not
support Terraform version 0.14.8. To proceed, either choose another supported
Terraform version or update this version constraint. Version constraints are
normally set for good reason, so updating the constraint may lead to other
errors or unexpected behavior.
```

terraform --version
Terraform v0.14.8

I was trying to work around this error but different errors follow.

Any suggestions and which the version of terraform is good for this example? Thanks.

**Comment by cf250024** [comment]
The workaround is here https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1121

- Terraform v0.12.29

- module "eks" {
      version = "~> 13.0.0"
      ......
    }

**Comment by cf250024** [comment]
@salvis2  I continue trying to figure out the issues with all the versions from different components for aws-examples/blog-post/aws.

Actually I found that if we don't specify any version requirements and it works fine.

Not sure if you want outsider to create PR for that?
1. Remove versions.
2. fix helm deprecation in the current code.

With that, I can run `terraform init` and `terraform plan` without problems.
Please give me permission to create PR and let the team to review if it's okay with the team.

```
terraform version
Terraform v0.14.9
+ provider registry.terraform.io/hashicorp/aws v3.35.0
+ provider registry.terraform.io/hashicorp/helm v2.1.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.3
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

```

**Comment by salvis2** [comment]
Hey @cf250024 , thanks for raising this issue. 

It seems like installing Terraform v0.12.6 would be the first thing to try, since the first error message complains about Terraform v0.14.8. I don't want change the `blog-post` example, since that is attached to a blog post that I am not going to update. The Terraform version should stay as it is. If you can find some versions of the modules that cooperate with Terraform v0.12.6, that would be better.

**Comment by cf250024** [comment]
@salvis2 Thanks for your reply. I agree that you plan to keep Terraform version to v0.12.6 to match blog-post as long as other providers using particular versions.

Here are a few points I am trying to figure out and appreciate if you can help me out.

- I guess helm URL has to be updated to the new one as "https://charts.helm.sh/stable" since the old one is not working anymore.
- Not sure why there are no nodes in the cluster and all the pods are pending without node to schedule on at the beginning. When does the autoscaler kicked in? (Note: I found That the reason of node not joining to cluster is due to kubelet deprecation of node labels for k8s 1.8 with this pr https://github.com/kubernetes/kubernetes/pull/79305. So we have to remove the label `*.kubernetes.io/*` otherwise kubelet service is not running and hence the node is not joined. Will figure out the impact of this removed label and hopefully it doesn't affect cluster autoscaler. Added note: it seems role.kubernetes.io/* label was added for spot instance gracefully termination. Need more research on how to handle it now without this label? ) 
- I tried and noticed there are 2  storage classes (gp2 as the default and efs). Not sure what the considerations are when using efs-provisoner. Also seems efs-provisoiner chart and image are deprecated and no more support. Any plans on this? (update: the new project helm chart is at https://github.com/kubernetes-sigs/aws-efs-csi-driver and my fork has working version with efs-csi-driver.)

My guess is your team has already put these in production which is very impressive. Definitely I'll learn from your experience. 
BTW, I pushed those changes to my fork.
